language: bash

dist: xenial

before_install:
  - rm -rf ~/.gnupg

before_script:
  - sudo rm -rf /etc/mysql/
  - sudo bash -c 'echo example.com > /etc/hostname'
  - sudo apt-get -qq purge mysql* graphviz*
  - sudo apt-get -qq autoremove
  - sudo apt-get update

script:
  - lsb_release -a
  - unset LANG
  - sudo bash -c 'echo -e "[user]\n\tname = abc\n\temail = root@localhost.com" > /home/travis/.gitconfig'
  - sudo echo "Travis Banch = $TRAVIS_BRANCH"
  - sudo apt-get install -y --force-yes git python3-setuptools python3-dev python3-apt
  - sudo bash install $TRAVIS_BRANCH
  - sudo wo --help
  - sudo wo stack install || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo stack install --web || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo stack install --admin || sudo tail -n50 /var/log/wo/wordops.log

  - sudo wo site create html.net --html || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site create php.com --php || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site create mysql.com --mysql || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site create site1.com --wp || sudo tail -n50 /var/log/wo/wordops.log

  - sudo wo site create site2.net --wp --wpsc || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site create site4.com --wpfc || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site create site4.net --wp --wpfc || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site create site4.org --wpfc --wp || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site create site5.com --wpsubdir || sudo tail -n50 /var/log/wo/wordops.log

  - sudo wo site create site6.com --wpsubdir --wpsc || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site create site8.com --wpsubdir --wpfc || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site create site8.net --wpfc --wpsubdir || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site create site9.com --wpsubdomain || sudo tail -n50 /var/log/wo/wordops.log

  - sudo wo site create site10.org --wpsubdomain --wpsc || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site create site12.org --wpsubdomain --wpfc || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site create site12.in --wpfc --wpsubdomain || sudo tail -n50 /var/log/wo/wordops.log

  - yes | sudo wo site create site.hhvm.pagespeed2.com --wpsc --hhvm || sudo tail -n50 /var/log/wo/wordops.log
  - yes | sudo wo site create site.hhvm.pagespeed4.com --wpfc --hhvm || sudo tail -n50 /var/log/wo/wordops.log
  - yes | sudo wo site create site.hhvm.pagespeed5.com --wpsubdir --hhvm || sudo tail -n50 /var/log/wo/wordops.log
  - yes | sudo wo site create site.hhvm.pagespeed6.com --wpsubdir --wpsc --hhvm || sudo tail -n50 /var/log/wo/wordops.log
  - yes | sudo wo site create site.hhvm.pagespeed8.com --wpsubdir --wpfc --hhvm || sudo tail -n50 /var/log/wo/wordops.log
  - yes | sudo wo site create site.hhvm.pagespeed9.com --wpsubdomain --hhvm || sudo tail -n50 /var/log/wo/wordops.log
  - yes | sudo wo site create site.hhvm.pagespeed10.org --wpsubdomain --wpsc --hhvm || sudo tail -n50 /var/log/wo/wordops.log
  - yes | sudo wo site create site.hhvm.pagespeed12.in --wpfc --wpsubdomain --hhvm || sudo tail -n50 /var/log/wo/wordops.log

  - sudo wo site create site1.localtest.me --php --mysql || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site create site2.localtest.me --mysql --html || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site create site3.localtest.me --php --html || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site create site4.localtest.me --wp --wpsubdomain || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site create site5.localtest.me --wp --wpsubdir --wpfc || sudo tail -n50 /var/log/wo/wordops.log
  - yes | sudo wo site create site6.localtest.me --wpredis || sudo tail -n50 /var/log/wo/wordops.log
  - yes | sudo wo site create site7.localtest.me --wpsubdomain --wpredis || sudo tail -n50 /var/log/wo/wordops.log
  - yes | sudo wo site create site8.localtest.me --wpsubdir --wpredis || sudo tail -n50 /var/log/wo/wordops.log


  - sudo wo debug --all || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo debug --all=off || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo debug site12.net || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo debug site12.net --all=off || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site create 1.com --html || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site create 2.com --php || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site create 3.com --mysql || sudo tail -n50 /var/log/wo/wordops.log

  - sudo wo site update 1.com --wp || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site update 2.com --wpsubdir || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site update 3.com --wpsubdomain || sudo tail -n50 /var/log/wo/wordops.log

  - sudo wo site update site1.com --wp --wpfc || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site update site1.com --wp --wpsc || sudo tail -n50 /var/log/wo/wordops.log
  - yes | sudo wo site update site1.com --wpredis || sudo tail -n50 /var/log/wo/wordops.log

  - sudo wo site update site5.com --wpsubdir --wpfc || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site update site5.com --wpsubdir --wpsc || sudo tail -n50 /var/log/wo/wordops.log

  - sudo wo site update site9.com --wpsubdomain --wpfc || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site update site9.com --wpsubdomain --wpsc || sudo tail -n50 /var/log/wo/wordops.log
  - yes | sudo wo site update site.hhvm.pagespeed12.in --hhvm=off || sudo tail -n50 /var/log/wo/wordops.log
  - yes | sudo wo site update site9.com --hhvm || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site info site.hhvm.pagespeed12.in || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site info site9.com || sudo tail -n50 /var/log/wo/wordops.log

  - sudo wo site create www.site-1.com --wp || sudo tail -n50 /var/log/wo/wordops.log|| sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site create www.subsite.site-1.com --wpfc || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site update www.subsite.site-1.com --wp || sudo tail -n50 /var/log/wo/wordops.log
  - sudo wo site delete www.subsite.site-1.com --all --no-prompt || sudo tail -n50 /var/log/wo/wordops.log

  - sudo wo site delete site12.in --all --no-prompt || sudo tail -n50 /var/log/wo/wordops.log

  - sudo ls /var/www/
  - sudo wp --allow-root --info
  - sudo bash -c 'cat /var/log/wo/wordops.log'
